#!/usr/bin/env bash
# keymaster/build.sh -- build the km-init arm64 deb.
#
# Contents of the deb:
#   /usr/sbin/km-init                       the daemon (this is userspace
#                                           ONLY; the qcomtee kernel
#                                           driver comes from the kernel
#                                           build, CONFIG_QCOMTEE=y)
#   /usr/lib/km-init/keymaster.img          stock-signed keymaster TA
#                                           (from the iceland-fw dumps)
#   /etc/km-init/values.conf                forged boot-state values
#                                           (conffile, generated by
#                                           values/km-extract-values.py)
#   /usr/lib/systemd/system/km-init.service + enable symlink
#
# libqcomtee (quic/quic-teec) is fetched as a pinned tarball and compiled
# straight into the binary; libcbor is linked statically from
# libcbor-dev, so the deb's runtime Depends is libc6 only.
#
# Everything compiles inside a one-shot stock docker.io/library/ubuntu:26.04
# linux/arm64 container (qemu on x86_64 hosts); apt cache under
# ../keymaster/apt-cache (relative to build/).
#
# Usage: ./build.sh [DEB_OUT_DIR]   (or OUT=... ./build.sh)
#   DEB_OUT_DIR defaults to ../../build/userspace/debs; the deb lands there
#   as km-init_<version>_arm64.deb.
#   KM_FW_DIR (default <repo>/repos/iceland-fw) provides keymaster.img;
#   the copy is pinned by SHA256 and verified on the host.
set -euo pipefail

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
META="${SCRIPTDIR}"
OUT="${OUT:-${SCRIPTDIR}/../../../build/userspace/debs}"

BASE="${BASE_IMAGE:-docker.io/library/ubuntu:26.04}"

# pinned inputs ------------------------------------------------------------
QUIC_TEEC_URL="https://github.com/quic/quic-teec/archive/736419e25a2036aac3292a10a93e394a90750ca3.tar.gz"
QUIC_TEEC_SHA256="887ace80e98c0dc67163a44fdd280c9a9cf0e46a9671ebf33643def261fc405a"
KEYMASTER_SHA256="0acc1861160078f582e0a308320aa6a11d1a5e8fc0dfc0ae7d774ab670f37085"

REPO_ROOT="${SCRIPTDIR}/../../.."
KM_FW_DIR="${KM_FW_DIR:-${REPO_ROOT}/repos/iceland-fw}"

while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help) sed -n '2,27p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) OUT="$1" ;;
    esac
    shift
done
mkdir -p "${OUT}"
OUT="$(cd "${OUT}" && pwd)"

log() { printf '[km-init-build] %s\n' "$*" >&2; }
die() { log "ERROR: $*"; exit 1; }

command -v podman >/dev/null 2>&1 || die "podman not found"
[ -f "${META}/src/km-init.c" ] || die "missing src/km-init.c"
[ -f "${META}/src/sha256.c" ] || die "missing src/sha256.c"
[ -f "${META}/debian/control" ] || die "missing debian/control"
[ -f "${KM_FW_DIR}/keymaster.img" ] || die "keymaster.img not found at ${KM_FW_DIR} (KM_FW_DIR=... to override)"

VER="$(awk '/^Version:/{print $2}' "${META}/debian/control")"
[ -n "${VER}" ] || die "cannot parse Version from debian/control"
DEB_NAME="km-init_${VER}_arm64.deb"

# pin verification happens on the host: the container only ever sees the
# exact files that passed the sums
[ "$(sha256sum "${KM_FW_DIR}/keymaster.img" | cut -d' ' -f1)" = "${KEYMASTER_SHA256}" ] \
    || die "keymaster.img pin mismatch (expected ${KEYMASTER_SHA256})"
log "keymaster.img pin verified"

CACHE="${SCRIPTDIR}/../../../build/userspace/keymaster/apt-cache"
STAGE="${SCRIPTDIR}/../../../build/userspace/keymaster/staging"
mkdir -p "${CACHE}/archives/partial" "${CACHE}/lists/partial" "${STAGE}"

log "building in a one-shot stock ${BASE} (linux/arm64) container"
podman run --rm \
    --platform linux/arm64 \
    -e QUIC_TEEC_URL="${QUIC_TEEC_URL}" \
    -e QUIC_TEEC_SHA256="${QUIC_TEEC_SHA256}" \
    -e DEB_NAME="${DEB_NAME}" \
    -v "${META}:/src:ro" \
    -v "${KM_FW_DIR}/keymaster.img:/keymaster.img:ro" \
    -v "${STAGE}:/stage" \
    -v "${CACHE}/archives:/var/cache/apt/archives" \
    -v "${CACHE}/lists:/var/lib/apt/lists" \
    --entrypoint /bin/bash \
    "${BASE}" -euo pipefail -c '
# ---- inside the one-shot arm64 container ---------------------------------
[ "$(uname -m)" = aarch64 ] || { echo "not aarch64" >&2; exit 1; }
DEBIAN_FRONTEND=noninteractive
export DEBIAN_FRONTEND LC_ALL=C TZ=UTC

apt-get update
apt-get install -y --no-install-recommends gcc libc6-dev binutils curl ca-certificates libcbor-dev

# ---- fetch + verify the pinned libqcomtee sources -------------------------
mkdir -p /tmp/qteec && cd /tmp/qteec
curl -sL -o qteec.tar.gz "${QUIC_TEEC_URL}"
echo "${QUIC_TEEC_SHA256}  qteec.tar.gz" | sha256sum -c - || { echo "quic-teec pin mismatch" >&2; exit 1; }
tar xzf qteec.tar.gz
QTEEC=/tmp/qteec/quic-teec-736419e25a2036aac3292a10a93e394a90750ca3/libqcomtee

# ---- compile km-init (libqcomtee compiled straight in) --------------------
rm -rf /stage/pkg
mkdir -p /stage/pkg/usr/sbin /stage/pkg/usr/lib/km-init
LIBCBOR_A="$(cc -print-file-name=libcbor.a)"
if [ -f "${LIBCBOR_A}" ]; then CBOR="${LIBCBOR_A}"; else CBOR="-lcbor"; fi
cc -O2 -Wall -Wextra -o /stage/pkg/usr/sbin/km-init \
    /src/src/km-init.c /src/src/sha256.c \
    "${QTEEC}/src/qcomtee_object.c" \
    "${QTEEC}/src/objects/credentials_obj.c" \
    "${QTEEC}/src/objects/mem_obj.c" \
    -I"${QTEEC}/include" -I"${QTEEC}/src" -I/src/src \
    ${CBOR} -lpthread || exit 1
strip /stage/pkg/usr/sbin/km-init 2>/dev/null || true

# ---- acceptance: the shipped values must parse and derive -----------------
/stage/pkg/usr/sbin/km-init -t -c /src/rootfs/etc/km-init/values.conf \
    > /stage/values-dump.txt || exit 1
echo "[km-init-build] values self-test ok:"
sed "s/^/    /" /stage/values-dump.txt | head -6

# ---- assemble the package -------------------------------------------------
cp -a /src/rootfs/. /stage/pkg/
install -D -m 0644 /keymaster.img /stage/pkg/usr/lib/km-init/keymaster.img
mkdir -p /stage/pkg/etc/systemd/system/multi-user.target.wants
ln -sfn ../../../usr/lib/systemd/system/km-init.service \
    /stage/pkg/etc/systemd/system/multi-user.target.wants/km-init.service
' 2>&1 | grep -v '^$'

# ---- package on the HOST (guest tar stat fails under qemu-user) ------------
log "packing ${DEB_NAME} with the host dpkg-deb"
mkdir -p "${STAGE}/pkg/DEBIAN"
cp "${META}/debian/control" "${STAGE}/pkg/DEBIAN/control"
cp "${META}/debian/conffiles" "${STAGE}/pkg/DEBIAN/conffiles"
chmod 0644 "${STAGE}/pkg/DEBIAN/control" "${STAGE}/pkg/DEBIAN/conffiles"
chmod 0755 "${STAGE}/pkg/usr/sbin/km-init"

dpkg-deb --root-owner-group --build "${STAGE}/pkg" "${STAGE}/${DEB_NAME}"
dpkg-deb -I "${STAGE}/${DEB_NAME}" | head -15

cp -f "${STAGE}/${DEB_NAME}" "${OUT}/${DEB_NAME}"
log "built ${OUT}/${DEB_NAME}"
